// All Data
export const GET_DATA_LOADING = "GET_DATA_LOADING";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

// Cart data posting
export const ADD_DATA_LOADING = "ADD_DATA_LOADING";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const ADD_DATA_FAILURE = "ADD_DATA_FAILURE";

// Cart Data
export const CART_DATA_LOADING = "CART_DATA_LOADING";
export const CART_DATA_SUCCESS = "CART_DATA_SUCCESS";
export const CART_DATA_FAILURE = "CART_DATA_FAILURE";

// Remove from Cart
export const DELETE_CART_DATA_LOADING = "DELETE_CART_DATA_LOADING";
export const DELETE_CART_DATA_SUCCESS = "DELETE_CART_DATA_SUCCESS";
export const DELETE_CART_DATA_FAILURE = "DELETE_CART_DATA_FAILURE";
